Aquaveo/tethysext-atcore

.github/pull_request_template.md, tethysext/atcore/public/map_view/atcore_cesium_map_view.js, tethysext/atcore/services/map_manager.py
- Reorder the map_extent in the cesium map view 
- Did this in the JavaScript so the same extent can be used interchangeably between OpenLayers and Cesium MapView renderers.
N/A
=> Reorder the map_extent for Cesium version of MapView

tethysext/atcore/controllers/app_users/manage_resources.py, tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_resources.py
- Add resource type to app_user get_resources method to return the correct resource list.
=> - Manage resource only shows associated resource class.

tethysext/atcore/controllers/resources/tabs/summary_tab.py, tethysext/atcore/tests/integrated_tests/controllers/resources/tabs/summary_tab_tests.py
- Pass the managed session object to the get_summary_tab_info call.
=> Pass managed session to the get_summmary_tab_info call.

tethysext/atcore/controllers/resources/tabbed_resource_details.py, tethysext/atcore/tests/integrated_tests/controllers/resources/tabbed_resource_details_tests.py
- I fixed two instances where _handle_tab_action_request was not receiving the session as it should have been after refactoring in an earlier refactor.
=> Fix missed calls to _handle_tab_action_request that need session.

test.sh, tethysext/atcore/controllers/app_users/manage_resources.py, tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_resources.py, tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_users_tests.py
- Added the `resource_id` parameter (`r`) to the link from the manage  resource page to status page
- This filters the list of jobs to only those that have the `resource_id` in their `extended_properties`.
- Won't show all of the jobs that have ever run now
- Bonus: Fixed some tests that were failing in Python 3.6 and made test.sh less verbose.
=> Fix Resource Status Page to Only Show Jobs for One Resource

test.sh, tethysext/atcore/controllers/resources/tabs/files_tab.py, tethysext/atcore/public/resources/files_tab.js, tethysext/atcore/templates/atcore/resources/tabs/files_tab.html, tethysext/atcore/templates/atcore/resources/tabs/files_viewport_template.html, tethysext/atcore/templates/atcore/resources/tabs/tree_view_template.html, tethysext/atcore/tests/files/files_tab_tests/test_path_hierarchy_display_name/dir1/__meta__.json, tethysext/atcore/tests/files/files_tab_tests/test_path_hierarchy_display_name_error/dir1/__meta__.json, tethysext/atcore/tests/integrated_tests/controllers/resources/tabs/files_tab_tests.py
**Primary changes in this Pull Request:**
- Remove the `..` folder from the list
- Hide the `__meta__.json` file by default
- Add method/property that can be used to specify one or more regex patterns of files/folders to hide (e.g.: *.geojson to hide the __extent__.geojson)
- Have the FilesTab look for a display_name in meta and display that as the folder name for the file collection instead of it's ID if it is there.
**Please review the checklist before submitting the Pull Request:**
**Explain deviations from original design if applicable:**
- We were unable to lock the `..` folders to the top because DataTables can not do that. We removed them instead.
=> Files Tab Improvements

tethysext/atcore/models/app_users/organization.py, tethysext/atcore/tests/integrated_tests/services/app_users/condor_workflow_manager_tests.py
- Add `_attributes` column to Organizations model
- Add Attributes mixin to Organizations
=> Add ability to add arbitrary attributes to Organizations

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_input_mwv.py, tethysext/atcore/forms/widgets/param_widgets.py, tethysext/atcore/models/resource_workflow_steps/spatial_input_rws.py, tethysext/atcore/public/map_view/atcore_map_view.js, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_input_mwv_tests.py
Changed workflow validation errors to use attribute labels instead of titles.  Fixed post-processing of geojson in SpatialInputMWV, to include the drawing_layer name and sorting more feature types than just points.
- 
=> Agwa culvert workflow validation update and post-processing fixes

tethysext/atcore/services/workflow_manager/condor_workflow_manager.py, tethysext/atcore/tests/integrated_tests/services/app_users/condor_workflow_manager_tests.py
Added ability to generate jobs dynamically, by now allowing a function to be passed to the ResourceWorkflowCondorJobManager's jobs (along with the existing list of CondorWOrkflowJobNode or dict).
- 
=> Refactor HTCondor workflow manager to allow specifying jobs with a callback function

tethysext/atcore/controllers/app_users/resource_status.py, tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv_tests.py
- The Resource Status Jobs table was modified to only show logs for admin users.
- Job logs are not sanitized and can contain sensitive information like database passwords and usernames
=> Show Logs on Jobs Table Only for Admins

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py, tethysext/atcore/services/workflow_manager/condor_workflow_manager.py, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv_tests.py
Store the workflow in the condor workflow manager. Used in AGWA for being able to acces the workflow when using a callback function for dynamic jobs.
- 
=> Agwa_culvert_workflow_resource_workflow

tethysext/atcore/services/workflow_manager/condor_workflow_manager.py
Used by apps that utilize model groups.
When getting the model db url, if there is no database ID because the resource is a model group, use a placeholder db instead.  This will need to be initialized in the app's init command if used.
- 
=> Update to condor job manager for placeholder db.

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_dataset_mwv.py, tethysext/atcore/models/resource_workflow_steps/spatial_dataset_rws.py, tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.js, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_dataset_mwv_tests.py, tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_dataset_rws_tests.py
Updated SpatialDatasetMWV and SpatialDatasetRWS to allow for optional columns.  When an optional column is found to be empty, it is filled in with NODATA values.  Optional columns consisting entirely of NODATA values are not plotted.
- 
=> Allow optional columns for spatial datasets.

tethysext/atcore/controllers/app_users/manage_resources.py, tethysext/atcore/templates/atcore/components/resource_row.html
- Made resource group display in manage_resource optional
No tests for group functionality yet.
=> made resource group display optional

tethysext/atcore/templates/atcore/resources/tabs/summary_tab.html
For the details summary table, allow the two <td>'s (which contain a key and value) to have links on them.
- 
=> Allow links on summary tab table.

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py, tethysext/atcore/services/file_database.py, tethysext/atcore/tests/integrated_tests/services/file_database/file_collection_client_tests.py, tethysext/atcore/tests/integrated_tests/services/file_database/file_database_client_tests.py
- Adds new `relative_to` argument to the `FileCollectionClient.add_item()` and `FileDatabaseClient.new_collection()`.
- The relative item path will be preserved in the file collection relative to the `relative_to` path if provided.
=> File Collections can preserve relative paths of items added

tethysext/atcore/controllers/app_users/manage_resources.py
Previous commit got rid of resource.children when setting resource_card['children'] to empty list.
Keep the children around, they are needed when building child resources recursively.
If not enabling groups or no children, then we can set the resource_card children to an empty list.
- Enable list of models under parent.
=> Fix for displaying resource groups.

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_input_mwv.py, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_input_mwv_tests.py
- Allows use of 'attributes' option when simple input is needed.
- Allows a similar 'param_class' argument where more dynamic input is needed, via a request, session, or resource.
- The default is 'attributes' but 'param_class' is checked if 'attributes' is not used.
=> Added param_class option for SpatialInputMWV

tethysext/atcore/controllers/app_users/manage_resources.py, tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_resources.py
- Resources that had parents were not showing up on the manage resources page, even when grouping was disabled.
- Fixed an issue with the `ManageResources.get_resources()` method.
=> Fix Manage Resource Grouping Bug

tethysext/atcore/controllers/app_users/manage_resources.py, tethysext/atcore/templates/atcore/components/resource_row.html, tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_resources.py
- Allow different URLs to be specified for the ManageResources row/name link and the Launch button link via a new hook: `get_info_url()`.
- Make it easier to customize the icons and names of the different action buttons on ManageResources rows.
=> Separate launch and row links

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_input_mwv.py, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_input_mwv_tests.py
Fix getting the geoserver engine from the app, which is needed to create the coverage layer.
Updated test.
- 
=> SpatialInputMWV store_imagery fix.

tethysext/atcore/controllers/app_users/resource_status.py, tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py
- The jobs tables were DoSing the server b/c they would send a bunch of ajax calls every 5 seconds.
- Reduced how often they update status to every 30 seconds.
=> Reduce how often the jobs tables update status to reduce load on server

tethysext/atcore/controllers/resources/tabs/files_tab.py, tethysext/atcore/public/resources/files_tab.css, tethysext/atcore/public/resources/files_tab.js, tethysext/atcore/templates/atcore/resources/tabs/files_tab.html, tethysext/atcore/templates/atcore/resources/tabs/tree_view_template.html
* Fix sidebar
* New icons for expand/collapse buttons
* Expand folder tree by default
* Display top level collection contents by default
* Fix issue with clicking on name of folder to select
* Make text in address bar selectable
* Fix various whitespace issues
* Fix datatables css dependencies
* Add tool tips to buttons
N/A
=> Various fixes for the files tab

tethysext/atcore/controllers/resource_workflows/workflow_views/__init__.py, tethysext/atcore/controllers/resource_workflows/workflow_views/xms_tool_wv.py, tethysext/atcore/models/resource_workflow_steps/__init__.py, tethysext/atcore/models/resource_workflow_steps/xms_tool_rws.py, tethysext/atcore/tests/integrated_tests/__init__.py, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/workflow_views/xms_tool_wv_tests.py, tethysext/atcore/tests/integrated_tests/models/app_users/resource_workflow_tests/base_methods_tests.py
Added a new XMS tool ResourceWorkflowStep.  When an xmstool_class is specified, it will appear as a form on a ResourceWorkflowView with the different tool parameters.
Ex:
xmstool_step = XMSToolRWS(
name='XMS Tool',
order=10,
help='Run the xmsool',
options={
'xmstool_class': 'xms.tool.some_tool',
'form_title': 'XMS tool',
'renderer': 'django',
}
)
- 
=> Added XMS Tool resource workflow step and view

.github/workflows/push_on_commits_wo_tag.yml, .github/workflows/push_on_tag.yml, tethysext/atcore/controllers/app_users/mixins.py, tethysext/atcore/controllers/map_view.py, tethysext/atcore/controllers/resource_view.py, tethysext/atcore/controllers/resource_workflows/map_workflows/map_workflow_view.py, tethysext/atcore/controllers/resource_workflows/resource_workflow_router.py, tethysext/atcore/controllers/resource_workflows/results_views/dataset_workflow_results_view.py, tethysext/atcore/controllers/resource_workflows/results_views/map_workflow_results_view.py, tethysext/atcore/controllers/resource_workflows/results_views/plot_workflow_results_view.py, tethysext/atcore/controllers/resource_workflows/results_views/report_workflow_results_view.py, tethysext/atcore/controllers/resource_workflows/workflow_results_view.py, tethysext/atcore/controllers/resources/tabbed_resource_details.py, tethysext/atcore/mixins/__init__.py, tethysext/atcore/mixins/serialize_mixin.py, tethysext/atcore/models/app_users/resource.py, tethysext/atcore/models/app_users/resource_workflow.py, tethysext/atcore/models/app_users/resource_workflow_result.py, tethysext/atcore/models/app_users/resource_workflow_step.py, tethysext/atcore/tests/integrated_tests/__init__.py, tethysext/atcore/tests/integrated_tests/mixins/serialize_mixin_tests.py, tethysext/atcore/tests/integrated_tests/models/app_users/resource_workflow_tests/base_methods_tests.py, tethysext/atcore/tests/integrated_tests/urls/resources_tests.py, tethysext/atcore/utilities.py
- Implements a generalized Serialization mixin for Resource models.
- Allows derivative Resources to add custom fields to the serialized values.
- Adds get_url() method to ResourceWorkflow to assist with serialization.
=> Serialization Mixin

tethysext/atcore/public/map_view/atcore_cesium_map_view.js, tethysext/atcore/public/map_view/atcore_map_view.js, tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.js
Fixes issue of importing data into Chart Studio Cloud, which previously brought up this link when clicked on a plot: https://plotly.com/chart-studio-help/getting-data/
Updated plotlyServerURL for latest Chart Studio URL.
- 
=> Update plotly server url.

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_dataset_mwv.py, tethysext/atcore/models/resource_workflow_steps/spatial_dataset_rws.py, tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_dataset_rws_tests.py
Adding options to spatial dataset classes for fixed rows that didn't get added with changes to table input classes.  Fixes issues with spatial dataset input tables that defaulted to a fixed row number, even with max row counts being larger, allowing only a few rows to be entered.  Also fixes an issue where the add and delete row buttons were hidden.
Added options for fixed rows and numeric step (float precision) to spatial dataset classes that was added to the table input classes.  Both sets of classes use the same html, so it was working for the table input classes only.
- 
=> Fix issues with tables used by spatial dataset classes.

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_dataset_mwv.py, tethysext/atcore/models/resource_workflow_steps/spatial_dataset_rws.py, tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_dataset_mwv_tests.py, tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_dataset_rws_tests.py
Updated Spatial Dataset classes (RWS, MWV) to allow callback functions to be used for the template dataset and column options. Where these are used, we check to see if the option is a function or not, and call the function when that occurs. This allows a variable number of columns when setting up the template datasets in SpatialDatasetRWS steps. Desired plot columns, optional columns, and read only columns can also be customized with a callback function. A common use case would be for running a workflow in a resource group, providing a separate input column for each selected resource, along with plotting the data.
- 
=> Addition of Spatial Dataset Callbacks

tethysext/atcore/forms/widgets/param_widgets.py
- Set bounds for param.Integer in django forms
**For the parameter that doesn't have bounds,** I can input any number I want:
**For the parameter that has bounds**:
The spin buttons won't let me go beyond the range: 
=> Set bounds for param.Integer
