tethysext/atcore/controllers/resource_workflows/results_views/__init__.py
tethysext/atcore/models/app_users/resource_workflow_result.py
tethysext/atcore/public/map_view/atcore_cesium_map_view.js
tethysext/atcore/public/map_view/atcore_map_view.js
tethysext/atcore/tests/integrated_tests/models/app_users/resource_workflow_result_tests.py

- Fixed visibility and removing layer and legend bugs
- ResourceWorkflowResult controller can now be passed as a parameter

Steem 71 cesium map view

---

tethysext/atcore/mixins/meta_mixin.py
tethysext/atcore/models/file_database/file_collection.py
tethysext/atcore/models/file_database/file_database.py
tethysext/atcore/models/file_database/meta_mixin.py
tethysext/atcore/tests/files/file_collection_tests/test_read_meta/0aeeacc5-9a36-4006-b786-8b5089826bbc/120e22d4-32f2-4dac-832c-6995746f0fe7/__meta__.json
tethysext/atcore/tests/files/file_collection_tests/test_read_meta_bad_file/0aeeacc5-9a36-4006-b786-8b5089826bbc/120e22d4-32f2-4dac-832c-6995746f0fe7/__meta__.json
tethysext/atcore/tests/files/file_collection_tests/test_read_meta_overwrite/0aeeacc5-9a36-4006-b786-8b5089826bbc/120e22d4-32f2-4dac-832c-6995746f0fe7/__meta__.json
tethysext/atcore/tests/files/file_database_tests/test_read_meta/f0699b82-8ff4-4646-ab2b-cb43f137c3ac/__meta__.json
tethysext/atcore/tests/files/file_database_tests/test_read_meta_bad_file/e5bc841e-eeb7-4211-951f-d7e5a4ad08f2/__meta__.json
tethysext/atcore/tests/files/file_database_tests/test_read_meta_overwrite/f0699b82-8ff4-4646-ab2b-cb43f137c3ac/__meta__.json
tethysext/atcore/tests/integrated_tests/models/files_database/file_collection_tests.py
tethysext/atcore/tests/integrated_tests/models/files_database/file_database_tests.py

FileDatabase/FileCollection Meta Methods

---

test.sh
tethysext/atcore/tests/integrated_tests/__init__.py
tethysext/atcore/tests/integrated_tests/urls/app_users_tests.py
tethysext/atcore/tests/integrated_tests/urls/resources_tests.py
tethysext/atcore/urls/app_users.py
tethysext/atcore/urls/resources.py

This is a draft. Currently working on tests

resources urls

---

tethysext/atcore/controllers/app_users/manage_organizations.py
tethysext/atcore/controllers/app_users/manage_resources.py
tethysext/atcore/controllers/app_users/mixins.py
tethysext/atcore/controllers/app_users/modify_organization.py
tethysext/atcore/controllers/app_users/modify_resource.py
tethysext/atcore/controllers/app_users/resource_details.py
tethysext/atcore/controllers/app_users/resource_status.py
tethysext/atcore/models/app_users/resource.py
tethysext/atcore/templates/atcore/app_users/manage_organizations.html
tethysext/atcore/templates/atcore/app_users/manage_resources.html
tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_resources.py
tethysext/atcore/tests/integrated_tests/controllers/app_users/mixins.py
tethysext/atcore/tests/integrated_tests/controllers/app_users/modify_organization_tests.py
tethysext/atcore/tests/integrated_tests/controllers/app_users/resource_details_tests.py
tethysext/atcore/tests/integrated_tests/controllers/app_users/resource_status.py
tethysext/atcore/tests/integrated_tests/models/app_users/resource_tests.py
tethysext/atcore/tests/integrated_tests/urls/app_users_tests.py
tethysext/atcore/tests/integrated_tests/urls/resources_tests.py
tethysext/atcore/urls/resource_workflows.py
tethysext/atcore/urls/resources.py

resource url refactoring to handle multiple resources

Steem5 resource url v2

---

tethysext/atcore/templates/atcore/app_users/manage_resources.html

- Fixing a details link that wouldn't populate the href for the details correctly.
- N/A

Fix Details Link for Resources

---

tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_resources.py

- Fix a failing intermediate test.
- Remove an __init__ file that shouldn't have been added.
- [N/A] Bonus: Use TypeHints
- N/A

Fix Test and Remove __init__ File

---

tethysext/atcore/models/app_users/spatial_resource.py

update set_extent to allow user to pass in srid.

- Add srid option for set_extent

---

tethysext/atcore/models/app_users/spatial_resource.py

- update srid default value

---

tethysext/atcore/job_scripts/update_resource_status.py
tethysext/atcore/services/resource_condor_workflow.py
tethysext/atcore/tests/integrated_tests/services/resource_condor_workflow_tests.py

Update update_resource_status to use resource_class_path
Update ResourceCondorWorkflow class to take resource instance instead of resource_id
Update tests

Steem5 uploaddatasetworkflow

---

tethysext/atcore/models/app_users/spatial_resource.py
tethysext/atcore/tests/integrated_tests/models/app_users/spatial_resource_tests.py

- add test
_ add update_extent_srid to update srid for extent geom

Add update_extent_srid to update srid for extent geom

---

tethysext/atcore/controllers/resources/__init__.py
tethysext/atcore/controllers/resources/tabs/__init__.py
tethysext/atcore/controllers/resources/tabs/resource_list_tab.py
tethysext/atcore/public/resources/resource_list_tab.css
tethysext/atcore/templates/atcore/app_users/manage_resources.html
tethysext/atcore/templates/atcore/resources/tabs/resource_list_tab.html
tethysext/atcore/tests/integrated_tests/__init__.py
tethysext/atcore/tests/integrated_tests/controllers/resources/tabs/files_tab_tests.py
tethysext/atcore/tests/integrated_tests/controllers/resources/tabs/resource_list_tab_tests.py

**Primary changes in this Pull Request:**
- Add Resource List Tab
**Please review the checklist before submitting the Pull Request:**
**Explain deviations from original design if applicable:**
- N/A

Add Resource List Tab

---

tethysext/atcore/controllers/resources/tabs/resource_list_tab.py
tethysext/atcore/controllers/resources/tabs/summary_tab.py
tethysext/atcore/public/app_users/css/app_users.css
tethysext/atcore/services/resource_condor_workflow.py
tethysext/atcore/templates/atcore/app_users/manage_resources.html
tethysext/atcore/tests/integrated_tests/controllers/resources/tabs/resource_list_tab_tests.py

- Add get_href_for_resource() hook to ResourceListTab to allow developers to override the default href that is generated for the resource action href.
- Hide long descriptions on the manage resource pages.
- Change _staff_user to staff

STEEM Demo Fixes

---

tethysext/atcore/public/map_view/atcore_cesium_map_view.js
tethysext/atcore/templates/atcore/resources/tabs/resource_list_tab.html

- Hide long descriptions on Resource List Tab.
- Fix extent on Cesium Map View for the final time!

Additional Fixes from Demo

---

tethysext/atcore/tests/integrated_tests/controllers/map_view_tests.py

- Need to update convert geojson to shapefile method to work with pyshpe 2.

- Update test for atcore

---

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py
tethysext/atcore/controllers/resource_workflows/results_views/report_workflow_results_view.py
tethysext/atcore/handlers.py
tethysext/atcore/models/app_users/resource_workflow.py
tethysext/atcore/public/resource_workflows/panel_form_prep.js
tethysext/atcore/tests/integrated_tests/models/app_users/resource_workflow_tests/base_methods_tests.py

- update panel_form_prep.js to be able to handle multiple underscores. The previous one only replace one space with one underscore.
- Update get_tabular_data_for_previous_steps method to take request and session.
- Update get_tabular_data_for_previous_steps to return name instead of value if the name is defined in param
- Update test.

- Update atcore to work better with Param.

---

Dockerfile
tethysext/atcore/controllers/resource_workflows/results_views/map_workflow_results_view.py
tethysext/atcore/models/resource_workflow_results/spatial_workflow_result.py
tethysext/atcore/services/map_manager.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/results_views/map_workflow_results_view_tests.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_results/spatial_workflow_result_tests.py
tethysext/atcore/tests/unit_tests/services/map_manager.py

- Allow setting the times parameter when setting result WMS layers
- Fix results controller to add geojson layer to CesiumMapViews correctly.

Add Support for New MVLayer Times Parameter

---

tethysext/atcore/controllers/resource_workflows/results_views/report_workflow_results_view.py
tethysext/atcore/public/resource_workflows/report_workflow_results_view.js
tethysext/atcore/templates/atcore/resource_workflows/report_workflow_results_view.html
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/results_views/report_workflow_results_view_tests.py

Update report_workflow_results_view to include all the step's result into one map.

Steem72 report workflow results update

---

tethysext/atcore/controllers/map_view.py
tethysext/atcore/controllers/resource_workflows/map_workflows/map_workflow_view.py
tethysext/atcore/controllers/resource_workflows/results_views/map_workflow_results_view.py
tethysext/atcore/models/resource_workflow_results/spatial_workflow_result.py
tethysext/atcore/public/map_view/atcore_cesium_map_view.js
tethysext/atcore/services/map_manager.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv_tests.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/results_views/map_workflow_results_view_tests.py
tethysext/atcore/tests/integrated_tests/mixins/file_collections_controller_mixin_tests.py
tethysext/atcore/tests/integrated_tests/models/app_users/app_user_tests.py
tethysext/atcore/tests/integrated_tests/models/app_users/organization_tests.py
tethysext/atcore/tests/integrated_tests/services/app_users/condor_workflow_manager_tests.py
tethysext/atcore/tests/integrated_tests/services/resource_workflows/helpers_tests.py
tethysext/atcore/tests/integrated_tests/urls/resource_workflows_tests.py
tethysext/atcore/tests/unit_tests/services/map_manager.py

Support Model and Primitive for Cesium.
Update test.
Fix Lint.

Add Support for Cesium Models and Primitives

---

install.yml

Update sqlalchemy dependency to 1.4.* in install.yml
The code had already been updated in the previous PR.

Update sqlalchemy to 1.4

---

tethysext/atcore/controllers/app_users/modify_organization.py
tethysext/atcore/mixins/attributes_mixin.py
tethysext/atcore/models/app_users/organization.py
tethysext/atcore/templates/atcore/app_users/manage_organizations.html
tethysext/atcore/templates/atcore/app_users/manage_users.html
tethysext/atcore/templates/atcore/app_users/modify_organization.html
tethysext/atcore/templates/atcore/app_users/modify_resource.html
tethysext/atcore/tests/integrated_tests/services/app_users/condor_workflow_manager_tests.py

- Changes to make the `ModifyOrganization` controller and template extensible (for new and edit organization pages).
- Add `_attributes` field to the `Organization` model and adds `AttributeMixin` so arbitrary attributes can be saved to Organizations.
- Adds a `default` argument to the `get_attribute` method of the `AttributesMixin`. Default returned if the attribute is not found.
- Minor stylistic changes as part of AGWA review and clean up.

Customizable Modify Organizations Page

---

tethysext/atcore/controllers/resource_workflows/workflow_views/form_input_wv.py

Changed the way process_step_data handles incoming param data, which facilitates multi-select params on the form.
Uses form.cleaned_data instead of request.POST.get (which only returns the last item and not a list, which is needed for a multi-select param).
- 

Changed proccess_step_data to handle multi-select data

---

tethysext/atcore/resources/resource_workflows/update_status.py
tethysext/atcore/services/resource_workflows/decorators.py
tethysext/atcore/services/resource_workflows/helpers.py
tethysext/atcore/services/workflow_manager/condor_workflow_manager.py
tethysext/atcore/tests/integrated_tests/services/app_users/condor_workflow_manager_tests.py
tethysext/atcore/tests/integrated_tests/services/resource_workflows/helpers_tests.py

Refactored to handle extra arguments.
Refactored ResourceWorkflowCondorJobManager and workflow_step_job decorator, to handle extra arguments.  Updated parse_workflow_step_args to handle known and unknown (extra) arguments.
- 

Refactored ResourceWorkflowCondorJobManager and workflow_step_job decorator

---

tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.js

Removed commas being pasted in spatial_dataset_mwv
- 

Remove commas in numbers pasted

---

tethysext/atcore/models/resource_workflow_steps/spatial_dataset_rws.py
tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.js

Updated spatial_dataset_mwv.js script to allow more than one series on the preview plots.  Turned off static plot, allowing interaction, and hovering after plots to view values and series names.
- 

Adds multiple series plot preview on spatial dataset dialog

---

tethysext/atcore/controllers/app_users/manage_organizations.py
tethysext/atcore/controllers/app_users/manage_resources.py
tethysext/atcore/controllers/app_users/mixins.py
tethysext/atcore/controllers/app_users/modify_organization.py
tethysext/atcore/controllers/app_users/modify_resource.py
tethysext/atcore/templates/atcore/app_users/manage_resources.html
tethysext/atcore/templates/atcore/app_users/modify_organization.html
tethysext/atcore/tests/integrated_tests/controllers/app_users/manage_resources.py
tethysext/atcore/tests/integrated_tests/controllers/app_users/mixins.py
tethysext/atcore/tests/integrated_tests/controllers/app_users/modify_organization_tests.py
tethysext/atcore/tests/integrated_tests/controllers/app_users/modify_resource_tests.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/base.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/resource_workflow_router_tests.py
tethysext/atcore/tests/integrated_tests/urls/app_users_tests.py
tethysext/atcore/tests/integrated_tests/urls/resources_tests.py
tethysext/atcore/urls/app_users.py
tethysext/atcore/urls/resources.py

- Modify organizations view now handles multiple resources appropriately
- This required a fundamental refactor of the inner workings of ATCore

Multi resources organizations

---

tethysext/atcore/templates/atcore/app_users/modify_resource.html

Moved the block for the custom_field_help into the main block for the app_navigation_items.
- 

Fixed custom_field_help to be in the correct block

---

.github/workflows/push_on_commits_wo_tag.yml
.github/workflows/push_on_tag.yml
tethysext/atcore/tests/integrated_tests/models/resource_workflow_results/plot_workflow_result_tests.py

- Update the kaniko github action in attempt to resolve issue with build being killed prematurely.

Update the kaniko action version

---

tethysext/atcore/tests/integrated_tests/models/app_users/spatial_resource_tests.py

- Import func directly from sqlalchemy (recently removed from geoalchemy2.__init__)

Fix geoalchemy/sqlalchemy func import issue

---

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py
tethysext/atcore/models/resource_workflow_steps/spatial_condor_job_rws.py
tethysext/atcore/services/workflow_manager/condor_workflow_manager.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_condor_job_rws_test.py

Pass additional kwargs to the CondorJob through step config. For example the max_jobs argument.
- Add options in condor job step for passing CondorWorkflow kwargs

Add workflow_kwargs options to job steps

---

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py
tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_dataset_mwv.py
tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.js
tethysext/atcore/templates/atcore/resource_workflows/components/spatial_dataset_form.html

- Allow Organization Admins to view the job logs on the Condor Workflow view
- Don't show nodata values in dataset table forms

Various Changes Related to Feedback from AGWA Development

---

.github/workflows/push_on_commits_wo_tag.yml
Dockerfile
tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py
tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_data_mwv.py
tethysext/atcore/models/resource_workflow_results/spatial_workflow_result.py
tethysext/atcore/models/resource_workflow_steps/spatial_rws.py
tethysext/atcore/public/map_view/atcore_map_view.js
tethysext/atcore/services/map_manager.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/results_views/plot_workflow_results_view_tests.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_results/spatial_workflow_result_tests.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/results_rws_tests.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/set_status_rws_tests.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_attributes_rws_tests.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_condor_job_rws_test.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_dataset_rws_tests.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/spatial_input_rws_tests.py
tethysext/atcore/tests/unit_tests/services/map_manager.py
tethysext/atcore/urls/app_users.py

- Added capability for labeling spatial workflow result geojson layers.
- Updated map manager to handle passing the labeling data through.

Geojson Layer Labels for Some Workflow Views

---

tethysext/atcore/controllers/app_users/modify_resource.py
tethysext/atcore/templates/atcore/app_users/manage_resources.html

Add convenience variables
If groups are disabled, then the resources with parents will be rendered as rows on manage table.
also added variables for convenience when validating data and so forth.
- 

Fix issues w/ groups & children.

---

tethysext/atcore/controllers/app_users/modify_resource.py
tethysext/atcore/templates/atcore/app_users/manage_resources.html

- We added convenience variables for validate_custom_fields, but didn't add them to the function call.

Call convenience variables added in last pull request

---

install.yml
tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_input_mwv.py
tethysext/atcore/controllers/rest/spatial_reference.py
tethysext/atcore/models/resource_workflow_results/plot_workflow_result.py
tethysext/atcore/public/gizmos/spatial_reference_select/spatial_reference_select.css
tethysext/atcore/public/gizmos/spatial_reference_select/spatial_reference_select.js
tethysext/atcore/public/resource_workflows/spatial_input_mwv.css
tethysext/atcore/services/spatial_reference.py
tethysext/atcore/templates/atcore/resource_workflows/spatial_input_mwv.html
tethysext/atcore/templates/gizmos/spatial_reference_select.html
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_input_mwv_tests.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/workflow_views/form_input_wv_tests.py
tethysext/atcore/tests/integrated_tests/controllers/rest/spatial_reference.py
tethysext/atcore/tests/integrated_tests/models/app_users/resource_workflow_tests/base_methods_tests.py

Allow adding a spatial reference selector on the upload image modal of SpatialInputMWV.
Updated spatial reference controller to query WKT.
Updated failing tests due to updated python packages.
- 

Spatial reference updates for Spatial Input Workflow

---

tethysext/atcore/public/css/nav_tabs.css
tethysext/atcore/public/resource_workflows/workflow_results_tabs.css
tethysext/atcore/services/workflow_manager/condor_workflow_manager.py
tethysext/atcore/templates/atcore/components/nav_header.html

- make condor workflow manager work with no default model db
- fix some css issues with workflows:
* center back button arrow
* text color of active nav tab not white
* results tab alignment

Various Bug Fixes and Style Updates

---

.github/workflows/push_on_commits_wo_tag.yml
.github/workflows/push_on_tag.yml
tethysext/atcore/public/app_users/js/sort.js
tethysext/atcore/public/boostrap_spinner/css/bootstrap_spinner.css
tethysext/atcore/public/css/btn-fab.css
tethysext/atcore/public/css/center.css
tethysext/atcore/public/css/nav_header.css
tethysext/atcore/public/gizmos/slide_sheet/slide_sheet.css
tethysext/atcore/public/map_view/atcore_cesium_map_view.js
tethysext/atcore/public/map_view/atcore_map_view.css
tethysext/atcore/public/map_view/atcore_map_view.js
tethysext/atcore/public/resource_workflows/workflow_steps.css
tethysext/atcore/templates/atcore/app_users/manage_organizations.html
tethysext/atcore/templates/atcore/app_users/manage_resources.html
tethysext/atcore/templates/atcore/app_users/manage_users.html
tethysext/atcore/templates/atcore/components/layer_group_content.html
tethysext/atcore/templates/atcore/components/layer_item_content.html
tethysext/atcore/templates/atcore/components/nav_header.html
tethysext/atcore/templates/atcore/components/resource_row.html
tethysext/atcore/templates/atcore/map_view/map_view.html
tethysext/atcore/templates/atcore/pagination_template.html
tethysext/atcore/templates/atcore/resource_workflows/components/spatial_dataset_form.html
tethysext/atcore/templates/atcore/resources/tabbed_resource_details.html
tethysext/atcore/templates/atcore/resources/tabs/files_tab.html
tethysext/atcore/templates/atcore/resources/tabs/files_viewport_template.html
tethysext/atcore/templates/atcore/resources/tabs/workflows.html
tethysext/atcore/tests/integrated_tests/controllers/map_view_tests.py

- 
- [ x] Pull request has a meaning full name (not just the commit message from of your last commit)

migrate citywater to tethys4

---

tethysext/atcore/controllers/resource_workflows/workflow_views/xms_tool_wv.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_dataset_mwv_tests.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/workflow_views/xms_tool_wv_tests.py

Update xmstool argument handling due to an update of xmstool_core on 14 Feb 2024.  The xmstool_core change got rid of usage of param, and a switch over to a dict.
xmstool tests updated.
Updated test affected by recent tethys commit.
- 

xmstool argument update

---

tethysext/atcore/controllers/resource_workflows/workflow_views/form_input_wv.py
tethysext/atcore/forms/widgets/param_widgets.py
tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.css
tethysext/atcore/services/map_manager.py
tethysext/atcore/templates/atcore/resource_workflows/components/spatial_dataset_form.html
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/workflow_views/form_input_wv_tests.py

- Fix a bug in `form_input_wv.py`
- Fix a logic bug in `param_widgets.py`
- TableInput:
- Make read-only `td`s `readonly` instead of `disabled` in `spatial_dataset_form.html`
- add a style for read-only columns in `spatial_dataset_mwv.css`
- Add a `style` parameter for the function `build_wms_layer` in `map_manager.py`

Bug fixes for Land cover workflow

---

tethysext/atcore/services/file_database.py
tethysext/atcore/tests/integrated_tests/services/file_database/file_collection_client_tests.py

add has_item to FileCollectionClient

---

tethysext/atcore/controllers/resource_workflows/map_workflows/map_workflow_view.py
tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py
tethysext/atcore/controllers/resource_workflows/workflow_views/form_input_wv.py
tethysext/atcore/forms/widgets/param_widgets.py
tethysext/atcore/models/app_users/resource_workflow.py
tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.css
tethysext/atcore/services/file_database.py
tethysext/atcore/services/map_manager.py
tethysext/atcore/templates/atcore/resource_workflows/components/spatial_dataset_form.html
tethysext/atcore/templates/atcore/resource_workflows/spatial_condor_job_mwv.html
tethysext/atcore/tests/__init__.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/map_workflow_view_tests.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/workflow_views/form_input_wv_tests.py
tethysext/atcore/tests/integrated_tests/models/app_users/resource_workflow_tests/base_methods_tests.py
tethysext/atcore/tests/integrated_tests/services/file_database/file_collection_client_tests.py

- Hide the map if there's no spatial data to show
- Show data from steps `NDVI`, `VegetationTypes`, and `TableInput`

Spatial Condor Job Step Improvements

---

tethysext/atcore/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv.py
tethysext/atcore/models/resource_workflow_steps/xms_tool_rws.py
tethysext/atcore/templates/atcore/resource_workflows/spatial_condor_job_mwv.html
tethysext/atcore/tests/integrated_tests/urls/app_users_tests.py
tethysext/atcore/tests/integrated_tests/urls/resources_tests.py
tethysext/atcore/tests/integrated_tests/urls/spatial_reference.py

- Annotate the 'form-values` parameter of `XMSToolRWS` with `is_tabular` so it will be rendered in the preview page of job steps.
- The value of this parameter is a dictionary, so made spatial condor job step preprocess dictionaries recursively into HTML lists.

Better summary for XMS Tool steps

---

tethysext/atcore/controllers/resource_workflows/workflow_views/table_input_wv.py
tethysext/atcore/models/resource_workflow_steps/table_input_rws.py
tethysext/atcore/public/resource_workflows/spatial_dataset_mwv.js
tethysext/atcore/templates/atcore/resource_workflows/components/spatial_dataset_form.html
tethysext/atcore/tests/integrated_tests/models/resource_workflow_steps/table_input_rws_tests.py

- Add an option `fixed_rows` to TableInputRWS
- Hide the "add row button" and "delete row button" when fixed_rows is True
- Fix the table size when pasting if fixed_rows is True
Buttons are hidden:

Add an option fixed_rows to TableInputRWS

---

tethysext/atcore/controllers/app_users/modify_resource.py

- We were deleting children and parents even when doing nothing with relationships. I added a check to only do that if we were working with relationships.
Explain deviations from original design if applicable: N/A

fix an issue where we blow away children when we don't mean to.

---

tethysext/atcore/tests/integrated_tests/urls/app_users_tests.py
tethysext/atcore/tests/integrated_tests/urls/resource_workflows_tests.py
tethysext/atcore/tests/integrated_tests/urls/resources_tests.py
tethysext/atcore/tests/integrated_tests/urls/spatial_reference.py
tethysext/atcore/urls/app_users.py
tethysext/atcore/urls/resource_workflows.py
tethysext/atcore/urls/resources.py
tethysext/atcore/urls/spatial_reference.py
tethysext/atcore/utilities.py

- The primary goal from this PR is to update the url path of the UrlMap that matches the app' s index to `^$`. Test cases for urls have also been updating using Magic Mock instead of `None` or `Object` for mocking an app

Update the url path of the UrlMap path that matches the app' s index

---

tethysext/atcore/public/map_view/atcore_map_view.js

- Code cleanup for atcore_map_view.js

code cleanup for atcore_map_view

---

.github/workflows/push_on_commits_wo_tag.yml
tethysext/atcore/models/app_users/app_user.py
tethysext/atcore/tests/integrated_tests/controllers/resource_workflows/map_workflows/spatial_condor_job_mwv_tests.py
tethysext/atcore/tests/integrated_tests/models/app_users/app_user_tests.py
tethysext/atcore/tests/mock/django.py

- Updates get_app_user_from_request() so it uses the correct username for anonymous users.

Fix anonymous user

---

Dockerfile
install.yml

- Update docker image to use 4.3.6

Update to Tethys 4.3.6

---

Dockerfile
install.yml
tethysext/atcore/controllers/app_users/manage_resources.py
tethysext/atcore/public/resources/group_resources.js
tethysext/atcore/templates/atcore/app_users/manage_resources.html
tethysext/atcore/templates/atcore/components/resource_row.html

Make manage_resources.html and resource_row.html customizable

---

tethysext/atcore/services/model_db_spatial_manager.py
tethysext/atcore/tests/integrated_tests/services/spatial_reference.py
tethysext/atcore/tests/unit_tests/services/model_db_spatial_manager.py

This error happens when I resubmit a job.

Bugfix: Error the store already exists

---

docker/salt/tethys_atcore.sls

- Set CSRF_TRUSTED_ORIGINS setting in tethys_atcore.sls

Set CSRF_TRUSTED_ORIGINS setting in tethys_atcore.sls

---

tethysext/atcore/services/workflow_manager/condor_workflow_manager.py

- Update the docstring of validate_jobs

Update docstring of validate_jobs

---

tethysext/atcore/models/resource_workflow_results/plot_workflow_result.py
tethysext/atcore/tests/integrated_tests/models/resource_workflow_results/plot_workflow_result_tests.py

Add a bar plot option for `plot_type` of PlotWorkflowResult

Add a bar plot to PlotWorkflowResult

---

.github/workflows/push_on_commits_wo_tag.yml
.github/workflows/push_on_tag.yml
Dockerfile
install.yml

- Implements a matrix builds that are based on Tethys Version x Python Version x Django Version
- This matrix is used for Docker Builds, Unit Tests and Startup Tests

Implement Matrix Builds and Testing for ATCore
